My todo app
isaachinman/todo-app pull request #3
Opened 2019-02-27 13:50 UTC by shak-m

New PR for some additional functionality including toggling checkbox for completed todos.

2019-02-27 14:02 UTC, isaachinman requested changes

2019-02-27 14:02 UTC, isaachinman commented on src/App.js
> +    //probably a better way to do this but took me a while to get this working
Please use `Array.map`.

2019-02-28 14:10 UTC, shak-m commented on src/App.js
> +    //probably a better way to do this but took me a while to get this working
Change for map method made 👍

2019-02-28 15:01 UTC, isaachinman approved these changes

2019-02-28 15:01 UTC, merged